IF EXISTS (SELECT * FROM SYS.DATABASES WHERE NAME = 'QALight')
BEGIN
    DECLARE @Msg VARCHAR(100)
    SET @Msg = 'DB QALight already exists!'
    PRINT @Msg
    RAISERROR(@Msg, 20, 1) WITH LOG
END
GO

CREATE DATABASE QALight
GO

USE QALight
GO

CREATE TABLE SUBJECTS(
    ID int NOT NULL,
    NAME nchar(32) NULL,
    HOURS int NULL,
    SEMESTER smallint NULL,
 CONSTRAINT PK_SUBJECTS PRIMARY KEY (	ID ASC )
)
GO 

CREATE TABLE UNIVERSITIES(
    ID int NOT NULL,
    NAME nvarchar(150) NULL,
    RATING int NULL,
    CITY nvarchar(32) NULL,
 CONSTRAINT PK_UNIVERSITIES PRIMARY KEY (	ID ASC )
)
GO

CREATE TABLE EXAM_MARKS(
    ID int IDENTITY(1,1) NOT NULL,
    STUDENT_ID int NULL,
    SUBJ_ID int NULL,
    MARK decimal(5,3) NULL,
    EXAM_DATE datetime NULL,
 CONSTRAINT PK_EXAM_MARKS PRIMARY KEY ( ID ASC )
)
GO

CREATE TABLE SUBJ_LECT(
    LECTURER_ID int NOT NULL,
    SUBJ_ID int NOT NULL
 CONSTRAINT PK_SUBJ_LECT PRIMARY KEY ( LECTURER_ID ASC, SUBJ_ID ASC )
)
GO

CREATE TABLE LECTURERS(
    ID int NOT NULL,
    SURNAME nvarchar(50) NULL,
    NAME nvarchar(30) NULL,
    CITY nvarchar(50) NULL,
    UNIV_ID int NULL,
 CONSTRAINT PK_LECTURERS PRIMARY KEY ( ID ASC )
)
GO

CREATE TABLE STUDENTS(
    ID int NOT NULL,
    SURNAME nvarchar(50) NULL,
    NAME nvarchar(30) NULL,
    GENDER nchar(1) NULL,
    STIPEND decimal(18, 2) NULL,
    COURSE smallint NULL,
    CITY nvarchar(50) NULL,
    BIRTHDAY datetime NULL,
    UNIV_ID int NULL,
 CONSTRAINT PK_STUDENTS PRIMARY KEY ( ID ASC )
)
GO

CREATE TABLE STUDENTS_ARCHIVE(
    ID int NULL,
    SURNAME nvarchar(50) NULL,
    NAME nvarchar(30) NULL,
    GENDER nchar(1) NULL,
    STIPEND decimal(18, 2) NULL,
    COURSE smallint NULL,
    CITY nvarchar(50) NULL,
    BIRTHDAY datetime NULL,
    UNIV_ID int NULL
)
GO

ALTER TABLE EXAM_MARKS  WITH CHECK ADD  CONSTRAINT FK_EXAM_MARKS_STUDENT FOREIGN KEY(STUDENT_ID)
REFERENCES STUDENTS (ID)
GO

ALTER TABLE EXAM_MARKS CHECK CONSTRAINT FK_EXAM_MARKS_STUDENT
GO

ALTER TABLE EXAM_MARKS  WITH CHECK ADD  CONSTRAINT FK_EXAM_MARKS_SUBJECT FOREIGN KEY(SUBJ_ID)
REFERENCES SUBJECTS (ID)
GO

ALTER TABLE EXAM_MARKS CHECK CONSTRAINT FK_EXAM_MARKS_SUBJECT
GO

ALTER TABLE SUBJ_LECT  WITH CHECK ADD  CONSTRAINT FK_SUBJ_LECT_LECTURER FOREIGN KEY(LECTURER_ID)
REFERENCES LECTURERS (ID)
GO

ALTER TABLE SUBJ_LECT CHECK CONSTRAINT FK_SUBJ_LECT_LECTURER
GO

ALTER TABLE SUBJ_LECT  WITH CHECK ADD  CONSTRAINT FK_SUBJ_LECT_SUBJECT FOREIGN KEY(SUBJ_ID)
REFERENCES SUBJECTS (ID)
GO

ALTER TABLE SUBJ_LECT CHECK CONSTRAINT FK_SUBJ_LECT_SUBJECT
GO

ALTER TABLE LECTURERS  WITH CHECK ADD  CONSTRAINT FK_LECTURERS_UNIV FOREIGN KEY(UNIV_ID)
REFERENCES UNIVERSITIES (ID)
GO

ALTER TABLE LECTURERS CHECK CONSTRAINT FK_LECTURERS_UNIV
GO

ALTER TABLE STUDENTS  WITH CHECK ADD  CONSTRAINT FK_STUDENTS_UNIV FOREIGN KEY(UNIV_ID)
REFERENCES UNIVERSITIES (ID)
GO

ALTER TABLE STUDENTS CHECK CONSTRAINT FK_STUDENTS_UNIV
GO
